//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.Web.Mvc;

    public partial class Food
    {
        [Key]
        public int Id { get; set; }

        [Display(Name = "Prekė")]
        [Required(ErrorMessage ="Reikia įvesti prekės pavadinimą")]
        public string Item { get; set; }

        [Display(Name ="Prekės kiekis")]
        [Required(ErrorMessage ="Reikia įvesti prekės kiekį")]
        public string Quantity { get; set; }

        [Display(Name ="Pastabos")]
        public string Notes { get; set; }

        [Display(Name ="Prekės tipas")]
        [Required(ErrorMessage ="Reikia įvesti prekės tipą - maistas 0, kitos prekės 1")]
        public int Type { get; set; }

        [Required]
        public bool Softdel { get; set; }
        public string Selection { get; set; }
    }

    
}
