//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodMVC.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Food
    {
        [Key]
        public int Id { get; set; }

        [Required(ErrorMessage ="Reikia įvesti prekės pavadinimą")]
        [Display(Name ="Prekė")]
        public string Item { get; set; }

        [Required(ErrorMessage ="Reikia įvesti kiekį")]
        [Display(Name ="Kiekis")]
        public string Quantity { get; set; }

        [Display(Name ="Pastabos")]
        public string Notes { get; set; }

        [Required]
        public int Type { get; set; }

        [Required]
        public bool Softdel { get; set; }
    }
}
