//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodMVC.Models
{
    using System;
    using System.ComponentModel.DataAnnotations;

    public partial class LogReg
    {
        [Key]
        public int Id { get; set; }

        [Display(Name ="Vartotojo vardas")]
        [Required(ErrorMessage ="Reikia įvesti vartotojo vardą")]
        public string UserName { get; set; }

        [Display(Name = "Slaptažodis")]
        [Required(ErrorMessage = "Reikia įvesti slaptažodį")]
        [DataType(DataType.Password)]
        public string Password { get; set; }

        [Display(Name ="El. pašto adresas")]
        [Required(ErrorMessage ="Reikia suvesti el. pašto adresą")]
        [DataType(DataType.EmailAddress)]
        public string Email { get; set; }

        [Required]
        [Display(Name = "Vartotojo tipas")]
        public string Role { get; set; }

        [Display(Name = "Dabar")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        public DateTime ResentTime { get; set; } = DateTime.Now.AddHours(2);

        [Display(Name = "Paskutinis prisijungimas")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        public Nullable<System.DateTime> LastLog { get; set; }

        [Display(Name ="Paskkutinis pakeitimas")]
        [DisplayFormat(ApplyFormatInEditMode = true, DataFormatString = "{0:yyyy-MM-dd HH:mm}")]
        public Nullable<System.DateTime> LastMod { get; set; }
    }
}
