//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FoodMVC.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Time
    {
        public int Id { get; set; }
        public DateTime ResentTime { get; set; } = DateTime.Now;
        public DateTime LogTime { get; set; }
        public DateTime ModTime { get; set; }
    }
}
